// <auto-generated />
namespace DrugBot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adduserloanstuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduserloanstuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201701072215283_add-user-loan-stuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
